---
title: "Progressive ILD RBC Chemical Shift"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tidymodels)
library(openintro)
library(janitor)
```

```{r}
#Read In CSVs
"007s_data" <- read_csv("/Users/anuraganugu/Documents/spectroscopy_combined_007s.csv")
"009s_data" <- read_csv("/Users/anuraganugu/Documents/spectroscopy_combined_009s.csv")
```

```{r}
#Remove the S1s and S2s from the csv that are incorrect
`007s_data_filtered` <- `007s_data` |>
  slice(-c(78, 80, 81, 83))
```

```{r}
#Filter out S2 scans
`007s_data_filtered` <- `007s_data_filtered`|>
  filter(!grepl("s2", subject_id, ignore.case = TRUE))
```

```{r}
#Remove string S1
`007s_data_filtered` <- `007s_data_filtered` |>
  mutate(subject_id = str_remove(subject_id, "_s1"), subject_id = str_remove(subject_id, "_S1"))
```

```{r}
#Remove outlier with abnormal RBC shift
`009s_data_filtered` <- `009s_data` |>
  slice(-c(202))
```

```{r}
#Combine dataframes
combined_spect_data <- bind_rows(`007s_data_filtered`, `009s_data_filtered`)
```

```{r}
#Create Timepoint and Subject Variable
combined_spect_data_transformed <- combined_spect_data |>
  mutate(
    timepoint = case_when(
      str_detect(subject_id, "A$") ~ "3 Months",
      str_detect(subject_id, "B$") ~ "6 Months",
      str_detect(subject_id, "C$") ~ "12 Months",
      TRUE ~ "Baseline"
    ),
    timepoint = factor(
      timepoint,
      levels = c("Baseline", "3 Months", "6 Months", "12 Months")
    )
  ) |>
  relocate(timepoint, .after = 1) |>
  mutate(subject = str_remove(subject_id, "[ABC]$")) |>
  relocate(subject, .after = 1) 
```

```{r}
#Summary Statistics
combined_spect_data_transformed |>
  group_by(timepoint) |>
  summarize(
    n = n(),
    mean = mean(rbc_shift, na.rm = TRUE),
    sd = sd(rbc_shift, na.rm = TRUE),
    median = median(rbc_shift, na.rm = TRUE)
  )
```

```{r}
#Make side-by-side boxplots
ggplot(combined_spect_data_transformed, aes(timepoint, rbc_shift)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.5) +
  labs(
    x = "Timepoint",
    y = "RBC Shift",
    title = "RBC Shift Across Treatment Timepoints"
  ) +
  theme_bw()
```

```{r}
#Make dataset needed for analysis between just baseline and 3 months
combined_spect_data_b_and_3m <- combined_spect_data_transformed |>
  filter(timepoint %in% c("Baseline", "3 Months")) |>
  group_by(subject) |>
  filter(all(c("Baseline", "3 Months") %in% timepoint)) |>
  ungroup()
```

```{r}
#Make spaghetti plot for baseline and 3 months
ggplot(combined_spect_data_b_and_3m,
       aes(x = timepoint,
           y = rbc_shift,
           group = subject)) +
  geom_line(alpha = 0.2) +
  geom_point(alpha = 0.5) +
  theme_bw() +
  labs(
    title = "RBC Shift: Baseline vs 3 Months",
    x = "",
    y = "RBC Shift"
  )
```

```{r}
#Pivot dataset wider
b_and_3m_wide <- combined_spect_data_b_and_3m |>
  select(subject, timepoint, rbc_shift) |>
  pivot_wider(
    id_cols = subject,
    names_from = timepoint,
    values_from = rbc_shift
  )
```

```{r}
#Create new variable called delta rbc shift (3 months-baseline)
b_and_3m_wide <- b_and_3m_wide |>
  mutate(
    delta_rbc_shift = `3 Months` - Baseline
  )
```

```{r}
#Get summary statistics for the delta_rbc
b_and_3m_wide|>
  select(delta_rbc_shift) |>
  summarize(
    n = n(),
    mean = mean(delta_rbc_shift, na.rm = TRUE),
    sd = sd(delta_rbc_shift, na.rm = TRUE),
    median = median(delta_rbc_shift, na.rm = TRUE)
  )
```


```{r}
#Create histogram for the delta
ggplot(b_and_3m_wide, aes(x = delta_rbc_shift)) +
  geom_histogram(bins = 15) +
  theme_bw() +
  labs(
    title = "Distribution of Delta RBC Shift",
    x = "Delta RBC Shift",
  )
```
```{r}
#Create Q-Q plot to see if it follows a normal distribution
qqnorm(b_and_3m_wide$delta_rbc_shift)
qqline(b_and_3m_wide$delta_rbc_shift)
```

```{r}
#paired t-test where average change is comparaed to 0
t.test(b_and_3m_wide$delta_rbc_shift, mu = 0)
```



